services:
  kong:
      # --- Build the custom image instead of pulling ---
      build:
        context: ./kong  # Directory containing the Dockerfile and plugin source
        dockerfile: kong.Dockerfile # The name of the Dockerfile within the context
      # image: kong/kong-gateway:latest # Remove this line
      # --- End Build Section ---

      container_name: kong-gateway
      environment:
        KONG_DATABASE: 'off'
        KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
        KONG_PROXY_LISTEN: 0.0.0.0:8000
        KONG_ADMIN_LISTEN: 0.0.0.0:8001
        KONG_LOG_LEVEL: debug # Keep for debugging plugin
        KONG_DECLARATIVE_CONFIG_SCHEMA_CACHE: 'off'

      ports:
        - "${GATEWAY_PORT:-80}:8000" # Use default 80 if GATEWAY_PORT not set
        - "${GATEWAY_ADMIN_PORT:-8001}:8001" # Use default 8001 if GATEWAY_ADMIN_PORT not set
      volumes:
        # Mount the configuration file ONLY
        - ./kong/config/kong.yaml:/etc/kong/kong.yaml:ro
      networks:
        - app-network